/*
project-root
    api
        auth.js
        restaurants.js
        users.js
    components
        dashboard.js
        modal.js
        restaurant.js
        ui.js
    css
        auth_style.css
        home_style.css
    html
        dashboard.html
        edit-pfp.html
        home.html
        login.html
        register.html
    utils
        fetchData.js
        helpers.js
        map.js
    main.js 
*/